/*
 * generated by Xtext
 */
package il.ac.idc.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JackUiModule extends il.ac.idc.lang.ui.AbstractJackUiModule {
	public JackUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
