/*
* generated by Xtext
*/
package il.ac.idc.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JackStandaloneSetup extends JackStandaloneSetupGenerated{

	public static void doSetup() {
		new JackStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

