/*
 * generated by Xtext
 */
package il.ac.idc.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JackRuntimeModule extends il.ac.idc.lang.AbstractJackRuntimeModule {

}
