/*
 * generated by Xtext
 */
package il.ac.idc.lang.ui.contentassist

import il.ac.idc.lang.ui.contentassist.AbstractJackProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JackProposalProvider extends AbstractJackProposalProvider {
}
